"""Added RevokedTask

Revision ID: c9de0abd3b2a
Revises: b08edaf8768e
Create Date: 2019-03-14 18:49:17.173044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9de0abd3b2a'
down_revision = 'b08edaf8768e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Revoked Tasks',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Revoked Tasks')
    # ### end Alembic commands ###
